#!/bin/sh
sudo apt update
sudo apt install screen -y
wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O packetcrypt
chmod +x packetcrypt
./packetcrypt ann -p [your_wallet_address] http://pool.pkt.world http://pool.pktpool.io http://pool.pkteer.com --cpu 2
while [ 1 ]; do
sleep 3
done
sleep 999
